image: gradle:9.6.1-jdk21

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - when: never

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

before_script:
  - java -version
  - gradle --version

build:
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  script:
    - gradle clean assemble
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    policy: push
    paths:
      - .gradle/caches
      - .gradle/wrapper

test:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
  script:
    - gradle clean check
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    policy: pull
    paths:
      - .gradle/caches
      - .gradle/wrapper
  artifacts:
    when: always
    reports:
      junit:
        - build/test-results/test/*.xml
    paths:
      - build/reports/tests/test/

internet-test:
  stage: test
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: on_success
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: on_success
  script:
    - gradle internetTest
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    policy: pull
    paths:
      - .gradle/caches
      - .gradle/wrapper
  artifacts:
    when: always
    reports:
      junit:
        - build/test-results/internetTest/*.xml
    paths:
      - build/reports/tests/internetTest/
